# I am so sorry about this.
# Sourced from https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/blob/master/en
# Somewhat more permissive/naive.
banned_words:
  ['asshole', 'fuck', 'cunt', 'nigger', 'cocksucker', 'faggot', 'beaner', 'kike']